name: HawkScan

on:
  push:
    branches:
      - main
      - quickscan

  pull_request:
    branches:
      - main
      
jobs:
  build-and-test:
    permissions:      
      security-events: write
      packages: read
      actions: read
      contents: read
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Run Vuln Node Express
        run: npm run start &

      - name: Run HawkScan
        env:
          HAWK_ENV: GitHub Actions
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
          SARIF_ARTIFACT: true
        continue-on-error: true
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          # codeScanningAlerts: true
          githubToken: ${{ github.token }}

      - name: Verify SARIF file
        run: |
          ls stackhawk.sarif || true
          echo === vvv stackhawk.sarif contents vvv === || true
          cat stackhawk.sarif || true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: stackhawk.sarif
          category: StackHawk    # Optional category for the results
